url: http://2021.code4lib.org
permalink: /:categories/:title
exclude: [vendor]
repository: code4lib/2021.codelib.org
future: true
timezone: America/New_York
sass:
  sass_dir: assets/_scss
include:
  - .well-known
keep_files:
  - .dat
  - dat.json
